import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { DatabaseSync } from "node:sqlite";
import pg from "pg";

export interface Sql {
  all<T>(text: string, params?: unknown[]): Promise<T[]>;
  get<T>(text: string, params?: unknown[]): Promise<T | undefined>;
  run(text: string, params?: unknown[]): Promise<void>;
}

const sqliteSchema = `
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    phone TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL,
    name TEXT NOT NULL,
    last_jid TEXT,
    lid TEXT,
    last_extract_message_id INTEGER NOT NULL DEFAULT 0
  );
  CREATE TABLE IF NOT EXISTS messages (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    initiative INTEGER NOT NULL DEFAULT 0,
    created_at INTEGER NOT NULL
  );
  CREATE TABLE IF NOT EXISTS memories (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    content TEXT NOT NULL,
    created_at INTEGER NOT NULL
  );
  CREATE TABLE IF NOT EXISTS initiative_log (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    outcome TEXT NOT NULL,
    reason TEXT NOT NULL,
    created_at INTEGER NOT NULL
  );
`;

const postgresSchema = [
  `CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL,
    name TEXT NOT NULL,
    last_jid TEXT,
    lid TEXT,
    last_extract_message_id INTEGER NOT NULL DEFAULT 0
  )`,
  `CREATE TABLE IF NOT EXISTS messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    initiative INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS memories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    content TEXT NOT NULL,
    created_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS initiative_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    outcome TEXT NOT NULL,
    reason TEXT NOT NULL,
    created_at BIGINT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS wa_auth (
    name TEXT PRIMARY KEY,
    value TEXT NOT NULL
  )`,
];

function withoutSslParams(url: string): string {
  const parsed = new URL(url);
  parsed.searchParams.delete("sslmode");
  parsed.searchParams.delete("channel_binding");
  return parsed.toString();
}

function sqlitePlaceholders(text: string): string {
  return text.replace(/\$\d+/g, "?");
}

export function openSqlite(path: string): Sql {
  mkdirSync(dirname(path), { recursive: true });
  const db = new DatabaseSync(path);
  db.exec("PRAGMA foreign_keys = ON");
  db.exec(sqliteSchema);
  const columns = db.prepare("PRAGMA table_info(users)").all() as Array<{ name: string }>;
  if (!columns.some((column) => column.name === "lid")) {
    db.exec("ALTER TABLE users ADD COLUMN lid TEXT");
  }
  return {
    all: async <T>(text: string, params: unknown[] = []) =>
      db.prepare(sqlitePlaceholders(text)).all(...(params as never[])) as T[],
    get: async <T>(text: string, params: unknown[] = []) =>
      db.prepare(sqlitePlaceholders(text)).get(...(params as never[])) as T | undefined,
    run: async (text, params = []) => {
      db.prepare(sqlitePlaceholders(text)).run(...(params as never[]));
    },
  };
}

export async function openPostgres(url: string): Promise<Sql> {
  pg.types.setTypeParser(20, (value) => Number(value));
  const pool = new pg.Pool({
    connectionString: withoutSslParams(url),
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 60_000,
    idleTimeoutMillis: 60_000,
  });
  pool.on("error", (error) => {
    console.error(`[diza] Neon: ${error.message}`);
  });
  await pool.query("SELECT 1");
  for (const statement of postgresSchema) {
    await pool.query(statement);
  }
  const keepAlive = setInterval(() => {
    pool.query("SELECT 1").catch((error: Error) => {
      console.warn(`[diza] Neon adormeceu: ${error.message}`);
    });
  }, 240_000);
  keepAlive.unref();
  return {
    all: async (text, params = []) => (await pool.query(text, params)).rows,
    get: async (text, params = []) => (await pool.query(text, params)).rows[0],
    run: async (text, params = []) => {
      await pool.query(text, params);
    },
  };
}
